"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

# 放置要执行py的列表
APP = ['ntfs.py']
# 存放所有要用到的文件资源，比如我放置文件夹，app所要显示的图片文件，以及自写模块放
DATA_FILES = ["logo.icns"]
OPTIONS = {
            'iconfile':'logo.icns',             # app的图标，必须为icns的格式，其他格式的话是不会显示出来的      
            'plist': {
                'CFBundleName'   : 'TNTFS',     # 应用名
                'CFBundleDisplayName': 'TNTFS', # 应用显示名
                'CFBundleVersion': '0.0.1',     # 应用版本号
                'CFBundleIdentifier' : 'TNTFS', # 应用包名、唯一标识
                'NSHumanReadableCopyright': 'Copyright © 2023 BJ-Tian. All rights reserved.',   # 可读版权
                'includes': ['subprocess', 'tkinter.*','tkinter.ttk']      # 第三方库放在这里。
            }
        }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
